/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as consensusSol from "./Consensus.sol";
export type { consensusSol };
import type * as coreSol from "./Core.sol";
export type { coreSol };
import type * as filecoinSol from "./Filecoin.sol";
export type { filecoinSol };
import type * as htsSol from "./HTS.sol";
export type { htsSol };
import type * as oracleSol from "./Oracle.sol";
export type { oracleSol };
