/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "StarQuestConsensusService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarQuestConsensusService__factory>;
    getContractFactory(
      name: "StarQuest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarQuest__factory>;
    getContractFactory(
      name: "StarQuestFilecoinStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarQuestFilecoinStorage__factory>;
    getContractFactory(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService__factory>;
    getContractFactory(
      name: "StarQuestHTS",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarQuestHTS__factory>;
    getContractFactory(
      name: "StarQuestOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarQuestOracle__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "StarQuestConsensusService",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarQuestConsensusService>;
    getContractAt(
      name: "StarQuest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarQuest>;
    getContractAt(
      name: "StarQuestFilecoinStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarQuestFilecoinStorage>;
    getContractAt(
      name: "IHederaTokenService",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IHederaTokenService>;
    getContractAt(
      name: "StarQuestHTS",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarQuestHTS>;
    getContractAt(
      name: "StarQuestOracle",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarQuestOracle>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
